<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 

    <script src="https://ajax.googleapis.com/ajax/libs/prototype/1.7.3.0/prototype.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/scriptaculous/1.9.0/scriptaculous.js"></script>
<script type="text/javascript">
   ( function($) {
        // we can now rely on $ within the safety of our "bodyguard" function
        $(document).ready( function() {
            var offset=0;
            var totalUsers=0;
            var from=1;
            var to=0;
            $('#sync_btn').on('click',function(){
               count();
            })
    function sync()
    {
        if(parseInt(offset)<=parseInt(totalUsers/2))
        {
            
            new Ajax.Request("<?php echo $this->getUrl('interakt_app/adminhtml_app/syncdata');?>",{
                method:'get',
                parameters:"count="+count+"&offset="+offset,
                onSuccess: function(transport){
                    if(transport.responseText)
                    {
                         if(transport.responseText=='error')
                        {
                             $('#total_users').text('Invalid app key or api key, Please check your app key or api key, Further you have any proble please <a href="mailto:support@interakt.co?Subject=Need help for Interakt Integration with WordPress site" target="_top">Drop us an Email');
                        }
                        else
                        {
                            to=from+2;
                             $('#total_users').text('Users synced from'+from+' to '+to);
                             from+=2;
                            offset=offset+29;
                            sync();
                        }

                    }
                }
            });
        }
        else
        {
            $('#total_users').text('All data has been sent.');
        }
    }
    function count() {
        if(parseInt(offset)>parseInt(totalUsers/2))
        {
            alert('Users already synced');
        }
        else
        {
            offset=1;
            new Ajax.Request("<?php echo $this->getUrl('interakt_app/adminhtml_app/');?>",{
                method:'get',
                onSuccess: function(transport){
                if (transport.responseText){
                    //alert(transport.responseText);
                    totalUsers=transport.responseText;
                    $('#interakt_app_settings').append('<span id="total_users" style="text-align:center;font-size:14px;">Total no. of users = '+totalUsers+'</br>Syncing User Data.</span>')
                    $('#row_interakt_app_settings_app_id').closest('table').before('<span style="text-align:center;font-size:20px;fon-weight:bold;">Please do not reload page, it will take some time, have patience.</span>');
                    sync();
                }
                }
            });
        }
    }
            
        } );
    } ) ( jQuery );
</script>